import React from 'react';
import { 
  FileText, 
  BookOpen, 
  CloudUpload, 
  Activity, 
  CheckCircle, 
  AlertTriangle, 
  ChartBar, 
  Layers,
  Calendar,
  Award,
  Hash,
  Search,
  ArrowRight,
  Clock,
  Info,
  ChevronUp,
  ChevronDown,
  Lightbulb,
  RefreshCw,
  Check,
  Link,
  ExternalLink
} from 'lucide-react';

// Icons mapping
export const Icons = {
  Manuscript: FileText,
  Bibliography: BookOpen,
  Upload: CloudUpload,
  Analyzing: Activity,
  Activity: Activity,
  Success: CheckCircle,
  CheckCircle: CheckCircle,
  Warning: AlertTriangle,
  AlertTriangle: AlertTriangle,
  Chart: ChartBar,
  Alignment: Layers,
  Recency: Calendar,
  Calendar: Calendar,
  Authority: Award,
  Numbers: Hash,
  Entities: Search,
  Search: Search,
  ArrowRight: ArrowRight,
  Layers: Layers,
  Clock: Clock,
  Info: Info,
  ChevronUp: ChevronUp,
  ChevronDown: ChevronDown,
  Lightbulb: Lightbulb,
  RefreshCw: RefreshCw,
  Check: Check,
  Link: Link,
  ExternalLink: ExternalLink
};
